### ISSUE TITLE
BRC Treelogs - add new sites to Results page

### ISSUE THREAD

**Issue by mjopocock** [BiologicalRecordsCentre/BRCtracker#107]
Hi @BirenRathod 
@DavidRoy 

Once you have added the 2 new sites to the data entry page, could you please change the results page.

I only want people to be able to see results from 1 site at a time. I think there are two possible ways of doing this:
Option 1. When people click on the results link, they are given a drop-down selection box to choose which of the 3 sites they view. Once selected, they then see the 3 tabs of results (right, left and upwards) for that site.
Option 2: Create a hierarchy of tabbed pages of the results, so people can choose one tab from the 3 that are labelled with the sites, and also choose one of the 3 tabs labelled 'looking upwards','left post','right post'.

Thanks,
Michael

**Comment by BirenRathod** [comment]
@mjopocock , @DavidRoy 

New sites have been added to the report as well. There is now dropdown list , so you can select the location and click filter button to get desire result. 
**Note:** If you select "Leigh woods - Bristol" location, it gets three records. This indicate that all previous records have been saved without location id in the database due to one location. I assumed all previous records should stored with "Leigh woods - Bristol" location id, if that is the case, do let me and I  will update all those records with "Leigh woods".

**Comment by DavidRoy** [comment]
@mjopocock can this one be closed?
