### ISSUE TITLE
Article 17 reporting for UK & Scotland

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/BRCtracker#17]
This folder contains my preliminary investigation of what's available:
P:/NEC04273_SpeciesDistribution/Workfiles/BRC Range Trends/article17

There's an RStudio project with my preliminary analysis, and a pair of markdown documents that are the basis of my discussions with JNCC and SNH.

So the next task is to collate the UK and national trends for each species on these lists.

**Comment by GPowney** [comment]
Output plots for UK and Scotland can be found here: W:\PYWELL_SHARED\Pywell Projects\BRC\Gary\Indicator 2018\trend summary package\output.  Looks like we will struggle to get reliable trends for the majority of the article 17 species, particularly for scotland.  I ran the plots for the 36 species identified at the end of your (@drnickisaac) markdown document. A summary of the long- and short-term trend estimates for the UK (NOTE: some groups were only run for GB, due to a lack of data), can be found here: W:\PYWELL_SHARED\Pywell Projects\BRC\Gary\Indicator 2018\trend summary package\trend_summary.

**Comment by drnickisaac** [comment]
Great start. Next steps:
- [ ] Calculate precision on all the trend estimates (1/(sd^2)) and add to the spreadsheet
- [ ] Pull through the Latin names, number of records and Charlie's 'Useable' flag and append to spreadsheet
- [ ] Create a Markdown document for pulling all these results together (I'll edit once it has the basics)

**Comment by GPowney** [comment]
Rather than a Markdown document I've built a shiny app to better illustrate the results. https://gpowney.shinyapps.io/article_17_trend_app/

**Comment by drnickisaac** [comment]
Great stuff. Thanks. Could you also add "Model useable" as a filter (above "species")

**Comment by drnickisaac** [comment]
A few extra items to add, if possible:
- [ ] a dropdown filter on the long-term precision
- [ ] total number of records for each species
- [ ] information (from Charlie's table) of the date first record*

*e.g. _Barbus barbus_ is probably many years after 1970, judging by the output.

**Comment by GPowney** [comment]
Shiny app updated with two new input selection options, one based on the precision of the long-term trend, the other based on whether the model is useable ("model_useable column").

**Comment by drnickisaac** [comment]
Super - looks really good now.

**Comment by drnickisaac** [comment]
I'm closing this issue as we've reported to JNCC. 
Gary's report is "Update on the production of the Biodiversity Indicators 2018" in 
W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\Indicators
There is some ongoing (separate) discussion with JNCC and SNH about what they want in future. We'll set up a separate issue about this.
