### ISSUE TITLE
Rules of Thumb for Occupancy Models - Year 2

### ISSUE THREAD

**Issue by AugustT** [BiologicalRecordsCentre/BRCtracker#44]
This is the sequel to #14 which was closed at the end of Year 1

We have a methodology in place for creating rules of thumb, the next steps are 

- [x] Meet to discuss what makes a 'good' or 'bad' model @mlogie @CharlieOuthwaite @drnickisaac @GPowney 
- [x] Refine the metrics to those that are generalisable
- [x] Run the model to create rules of thumb
- [x] Publish final RMarkdown

**Comment by AugustT** [comment]
Have had meeting with the 'modellers', I'm now coding up and extracting the agreed on metrics

**Comment by AugustT** [comment]
This has now been handed to @mlogie who is working with me and Michael to get to a final rule set

**Comment by mlogie** [comment]
Rmarkdown is in a good place.  I think I have now addressed all issues raised by Tom and Michael.
I propose uploading the Rmarkdown and my associated scripts to GitHub, with your approval @AugustT.

**Comment by mlogie** [comment]
All files uploaded to github.  I've edited the comments in my data assessment script (results_calculator.R) so that it can be used to calculate and plot what proportion of species can be modeled for any given data set, as discussed.  Readme added to explain the basics.  Metrics files from our data are up as a demonstration set.  Repository is here:
https://github.com/BiologicalRecordsCentre/RulesOfThumb

**Comment by drnickisaac** [comment]
I think the preprint on BiorXiv closes this issue
